export const DRS_WEB_HANDLER_URL =
  "https://drsdemo.mohanbarathi.com/DRSHandler.ashx";

export const DRS_API_LOCAL_URL = "http://drsapi:8880/api/";
export const DRS_API_WEB_URL = "https://drsapi.mohanbarathi.com/api";
//"https://43.241.70.70/plesk-site-preview/drsapi.mohanbarathi.com/api";

export const LOCAL_WEB_HANDLER_URL = "DRSHandler.ashx";

export const YEARS_TO_SHOW = 4;

export const LocationType = {
  //All: 0,
  State: 1,
  Region: 2,
  District: 3,
  Block: 4,
  Panchayat: 5,
  Village: 6,
};

export const HTTPstatus = {
  Unknown: -1, // Not a standard HTTPstatus
  Waiting: 0, // Not a standard HTTPstatus
  Loading: 100, // Using Continue:100, as Loadin:100
  Unauthorized: 401,
  NOTLOGGEDIN: 995,
  OK: 200,
  NoContent: 204,
};

export const HTTPstatusText = {
  Waiting: "Waiting ...",
  Loading: "Loading ...",
  OK: "Success",
  NOTLOGGEDIN: "NOT LOGGED IN ???",

  Unauthorized:
    "You are not logged in OR your session is timed out. You will be logged out in 3 seconds.",
  UnknownError: "Unknown Error",
};

export const reportData = {
  regions: [
    // { id: 2, name: "இராமநாதபுரம்" },
    // { id: 7, name: "இராமேஸ்வரம்" },
    // { id: 8, name: "கன்னியாகுமரி" },
    { id: 1, name: "தஞ்சை" },
    // { id: 6, name: "திருச்சி" },
    // { id: 3, name: "புதுக்கோட்டை" },
    // { id: 10, name: "புதுச்சேரி" },
    // { id: 4, name: "மதுரை" },
    // { id: 9, name: "வேலூர்" },
  ],
  ErrorCode: 200,
  User: null,
  Event: null,
  LocationList: null,
};

export const TblH = {
  h: [{ name: "one" }, { name: "two" }],
};

// 20230413172151
// https://localhost:44340/DRSHandler.ashx?mode=TEST
export const UserData = {
  cols: [
    // "ErrorCode",
    // "ErrorData",
    "Id",
    "Name",
    "Mobile",
    "Mobile1",
    "Email",
    // "ForceChangePassword",
    // "IsLoggedIn",
    // "DOJ",
    // "IsLocked",
    // "IsDeleted",
    "DesignationId",
    "LocationTypeId",
    "LocationId",
    "RoleId",
    //"Role",
    "LocationTypeName",
    "LocationName",
    "DesignationName",
    //"Salary",
    // "StateId",
    // "RegionId",
    // "DistrictId",
    // "BlockId",
    // "PanchayatId",
    // "VillageId",
    // "IsAdmin",
    // "IsSuperAdmin",
    // "IsStateAdmin",
    // "IsVillageIncharge",
    // "LocationDetail",
    "LocationId",
    "LocationTypeId",
    // "LocationTypeName",
    // "LocationName",
    // "StateId",
    // "RegionId",
    // "DistrictId",
    // "BlockId",
    // "PanchayatId",
    // "VillageId",
    // "StateName",
    // "RegionName",
    // "DistrictName",
    // "BlockName",
    // "PanchayatName",
    // "VillageName",
    // "ChildCount",
    // "Regions",
    // "Districts",
    // "Blocks",
    // "Panchayats",
    // "Villages",
  ],
  data: [
    {
      ErrorCode: 200,
      ErrorData: null,
      Id: 1,
      Name: "SKM",
      Mobile: "9841133266",
      Mobile1: null,
      Email: "a@b.com",
      ForceChangePassword: false,
      IsLoggedIn: false,
      DOJ: "2022-04-16T18:28:47.797",
      IsLocked: false,
      IsDeleted: false,
      DesignationId: 1,
      LocationTypeId: 1,
      LocationId: 1,
      RoleId: 0,
      Role: 0,
      LocationTypeName: null,
      LocationName: null,
      DesignationName: null,
      Salary: 1000,
      StateId: 0,
      RegionId: 0,
      DistrictId: 0,
      BlockId: 0,
      PanchayatId: 0,
      VillageId: 0,
      IsAdmin: false,
      IsSuperAdmin: false,
      IsStateAdmin: false,
      IsVillageIncharge: false,
      LocationDetail: {
        LocationId: 0,
        LocationTypeId: 0,
        LocationTypeName: null,
        LocationName: null,
        StateId: 0,
        RegionId: 0,
        DistrictId: 0,
        BlockId: 0,
        PanchayatId: 0,
        VillageId: 0,
        StateName: null,
        RegionName: null,
        DistrictName: null,
        BlockName: null,
        PanchayatName: null,
        VillageName: null,
        ChildCount: 0,
        Regions: [],
        Districts: [],
        Blocks: [],
        Panchayats: [],
        Villages: [],
      },
    },
    {
      ErrorCode: 200,
      ErrorData: null,
      Id: 2,
      Name: "Namasivayam",
      Mobile: "8248496277",
      Mobile1: null,
      Email: null,
      ForceChangePassword: false,
      IsLoggedIn: false,
      DOJ: "2022-04-16T18:28:47.797",
      IsLocked: false,
      IsDeleted: false,
      DesignationId: 1,
      LocationTypeId: 1,
      LocationId: 1,
      RoleId: 0,
      Role: 0,
      LocationTypeName: null,
      LocationName: null,
      DesignationName: null,
      Salary: 1000,
      StateId: 0,
      RegionId: 0,
      DistrictId: 0,
      BlockId: 0,
      PanchayatId: 0,
      VillageId: 0,
      IsAdmin: false,
      IsSuperAdmin: false,
      IsStateAdmin: false,
      IsVillageIncharge: false,
      LocationDetail: {
        LocationId: 0,
        LocationTypeId: 0,
        LocationTypeName: null,
        LocationName: null,
        StateId: 0,
        RegionId: 0,
        DistrictId: 0,
        BlockId: 0,
        PanchayatId: 0,
        VillageId: 0,
        StateName: null,
        RegionName: null,
        DistrictName: null,
        BlockName: null,
        PanchayatName: null,
        VillageName: null,
        ChildCount: 0,
        Regions: [],
        Districts: [],
        Blocks: [],
        Panchayats: [],
        Villages: [],
      },
    },
    {
      ErrorCode: 200,
      ErrorData: null,
      Id: 4,
      Name: "SELVARANGAM",
      Mobile: "9940699344",
      Mobile1: "9150393718",
      Email: null,
      ForceChangePassword: false,
      IsLoggedIn: false,
      DOJ: "2022-04-16T18:28:47.797",
      IsLocked: false,
      IsDeleted: false,
      DesignationId: 3,
      LocationTypeId: 1,
      LocationId: 1,
      RoleId: 0,
      Role: 0,
      LocationTypeName: null,
      LocationName: null,
      DesignationName: null,
      Salary: 1000,
      StateId: 0,
      RegionId: 0,
      DistrictId: 0,
      BlockId: 0,
      PanchayatId: 0,
      VillageId: 0,
      IsAdmin: false,
      IsSuperAdmin: false,
      IsStateAdmin: false,
      IsVillageIncharge: false,
      LocationDetail: {
        LocationId: 0,
        LocationTypeId: 0,
        LocationTypeName: null,
        LocationName: null,
        StateId: 0,
        RegionId: 0,
        DistrictId: 0,
        BlockId: 0,
        PanchayatId: 0,
        VillageId: 0,
        StateName: null,
        RegionName: null,
        DistrictName: null,
        BlockName: null,
        PanchayatName: null,
        VillageName: null,
        ChildCount: 0,
        Regions: [],
        Districts: [],
        Blocks: [],
        Panchayats: [],
        Villages: [],
      },
    },
    {
      ErrorCode: 200,
      ErrorData: null,
      Id: 6,
      Name: "Thyagarajan",
      Mobile: "9787299772",
      Mobile1: null,
      Email: null,
      ForceChangePassword: false,
      IsLoggedIn: false,
      DOJ: "2022-04-16T18:28:47.797",
      IsLocked: false,
      IsDeleted: false,
      DesignationId: 4,
      LocationTypeId: 3,
      LocationId: 2,
      RoleId: 0,
      Role: 0,
      LocationTypeName: null,
      LocationName: null,
      DesignationName: null,
      Salary: 7000,
      StateId: 0,
      RegionId: 0,
      DistrictId: 0,
      BlockId: 0,
      PanchayatId: 0,
      VillageId: 0,
      IsAdmin: false,
      IsSuperAdmin: false,
      IsStateAdmin: false,
      IsVillageIncharge: false,
      LocationDetail: {
        LocationId: 0,
        LocationTypeId: 0,
        LocationTypeName: null,
        LocationName: null,
        StateId: 0,
        RegionId: 0,
        DistrictId: 0,
        BlockId: 0,
        PanchayatId: 0,
        VillageId: 0,
        StateName: null,
        RegionName: null,
        DistrictName: null,
        BlockName: null,
        PanchayatName: null,
        VillageName: null,
        ChildCount: 0,
        Regions: [],
        Districts: [],
        Blocks: [],
        Panchayats: [],
        Villages: [],
      },
    },
  ],
};

// 20230415190401
// http://drsdemo:8080/DRSHandler.ashx?mode=TEST
export const DevoteeData = {
  tableConfig: {
    AllowEdit: true,
    ShowFooter: true,
    EditWidth: "150px",
  },
  columnConfig: [
    {
      Column: "Id",
      Hidden: false,
      Sortable: false,
      ShowSumInFooter: true,
      Width: "50px",
    },
    {
      Column: "Name",
      Hidden: false,
      Caption: "Devotee Name",
      Sortable: true,
      ShowSumInFooter: true,
      Width: "250px",
    },
    {
      Column: "Mobile",
      Hidden: false,
      Sortable: true,
      ShowSumInFooter: true,
      Width: "200px",
    },
    {
      Column: "CreatedByName",
      Hidden: false,
      Caption: "Added By",
      Sortable: true,
      ShowSumInFooter: true,
      Width: "300px",
    },
  ],
  data: [
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 1,
      Name: "Sunder",
      Mobile: "9841244550",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 2,
      Name: "Siva",
      Mobile: "9885645678",
      CreatedByName: "Namasivayam",
    },
    {
      Id: 3,
      Name: "sn",
      Mobile: "09941858109",
      CreatedByName: "Namasivayam",
    },
  ],
};
